# GitHub Actions Workflow for Complex Application
# This workflow automates the build, test, and deployment process
# It runs whenever code is pushed to the master branch

name: Deploy MultiDocker

# Define when this workflow should run
on:
  push:
    branches:
      - main  # Trigger on pushes to master branch

# Define the jobs to run
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v3  # Use the latest stable version of checkout action

      # Login to Docker Hub using secrets
      # These secrets should be configured in your GitHub repository settings
      - run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the React application using the development Dockerfile
      # This creates a Docker image for testing
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client

      # Run the test suite inside the Docker container
      # CI=true ensures the tests run in CI mode
      - run: docker run -e CI=true ${{ secrets.DOCKERHUB_USERNAME }}/react-test npm test

      # Build all service images
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multiclient ./client
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-nginx ./nginx
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-server ./server
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-worker ./worker

      # Push all images to Docker Hub
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multiclient
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-nginx
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-server
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-worker


      